<?xml version="1.0" encoding="UTF-8"?>
<definitions id="definitions" 
  xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL"
  xmlns:camunda="http://camunda.org/schema/1.0/bpmn"
  targetNamespace="Examples">
  
  <error id="myException" errorCode="test.bpmn.Event.Error.MyBusinessException"/>
  
  <process id="testCatchExceptionThrownByScriptTask" isExecutable="true">
  
    <startEvent id="theStart" />
    <sequenceFlow id="flow1" sourceRef="theStart" targetRef="ScriptTask" />
    
    <ScriptTask id="ScriptTask" scriptFormat="groovy">
      <script>
        throw new test.bpmn.Event.Error.MyBusinessException("This is a business exception, which can be caught by a BPMN Error Event.");
      </script>
    </ScriptTask>
    
    <boundaryEvent id="catchException" attachedToRef="ScriptTask">
      <errorEventDefinition errorRef="myException"/>
    </boundaryEvent>
    
    <sequenceFlow id="flow3" sourceRef="catchException" targetRef="escalatedExceptionTask" />
    
    <userTask id="escalatedExceptionTask" name="Escalated Exception Task" />
    <sequenceFlow id="flow4" sourceRef="ScriptTask" targetRef="theEnd" />
    
    <endEvent id="theEnd" />
    
  </process>

</definitions>